# Generated by Django 5.2.9 on 2025-12-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='description',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='image',
            new_name='main_image',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
        migrations.AddField(
            model_name='hotel',
            name='additional_images',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/extra/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='facilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='google_location_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rented_type',
            field=models.CharField(choices=[('full', 'Full Villa'), ('rooms', 'Individual Rooms')], default='rooms', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='social_media_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
