# Generated by Django 5.2.9 on 2025-12-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_description_hotel_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='additional_images',
        ),
        migrations.AddField(
            model_name='hotel',
            name='ical_link',
            field=models.URLField(blank=True, help_text='Booking.com iCal link for calendar sync', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='facilities',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rented_type',
            field=models.CharField(choices=[('full', 'Full Villa'), ('rooms', 'Individual Rooms')], default='rooms', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='core.facility'),
        ),
    ]
