# Generated by Django 5.2.9 on 2025-12-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_facility_remove_hotel_additional_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='ical_link',
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the hotel/villa', null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per night if rented as Full Villa', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='ac_type',
            field=models.CharField(choices=[('ac', 'Air Conditioned'), ('non_ac', 'Non-AC')], default='non_ac', max_length=10),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
