# Generated by Django 5.2.9 on 2025-12-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hotel_photo1_hotel_photo2_hotel_photo3_hotel_photo4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(blank=True, help_text='e.g., Booking.com, Agoda, Walk-in', max_length=50, null=True),
        ),
    ]
