# Generated by Django 5.2.9 on 2025-12-30 17:06

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_booking_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='google_location_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rented_type',
            field=models.CharField(choices=[('rooms', 'Individual Rooms'), ('full', 'Entire Villa')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='social_media_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('owner', 'Owner')], default='customer', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='ac_type',
            field=models.CharField(choices=[('ac', 'Air Conditioned'), ('non_ac', 'Non-AC')], max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.AddField(
            model_name='hotel',
            name='facilities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('wifi', 'WiFi'), ('parking', 'Parking'), ('pool', 'Swimming Pool'), ('gym', 'Gym'), ('spa', 'Spa'), ('restaurant', 'Restaurant'), ('bar', 'Bar'), ('ac', 'Air Conditioning'), ('tv', 'TV'), ('hotwater', 'Hot Water')], max_length=55),
        ),
    ]
