# Generated by Django 5.2.9 on 2026-01-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_booking_customer_remove_booking_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='facebook_page',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook Page Link'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='google_location_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
