# Generated by Django 5.2.9 on 2026-01-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_hotel_facebook_page_hotel_google_location_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='google_location_link',
            field=models.URLField(blank=True, null=True, verbose_name='Google Maps Link'),
        ),
    ]
