# Generated by Django 5.2.9 on 2026-01-08 16:33

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_hotel_google_location_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='facilities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('wifi', 'WiFi'), ('pool', 'Swimming Pool'), ('parking', 'Parking'), ('restaurant', 'Restaurant'), ('spa', 'Spa'), ('gym', 'Gym'), ('bar', 'Bar'), ('ac', 'Air Conditioning'), ('tv', 'TV'), ('hot_water', 'Hot Water'), ('room_service', 'Room Service')], max_length=69),
        ),
    ]
