# Generated by Django 5.2.9 on 2026-01-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitestats_alter_booking_user_alter_hotel_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('owner', 'Owner'), ('manager', 'Manager')], default='customer', max_length=20),
        ),
    ]
